---
title: "Baixando dados diários"
author: 
- Lucca Simeoni Pavan \hspace{1cm} João Carlos de Carvalho
header-includes:
   - \setlength\parindent{24pt}
   - \usepackage[english, brazil]{babel}
date: \today
output: 
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
bibliography: bib_artigo_macroeconometria.bib
---

```{r setup, include=TRUE, tidy = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE,
                warning = FALSE, message = FALSE, error = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 70))
```

# Ranking de negociações

```{r tickers}
library(GetHFData)
tickers_equity <- ghfd_get_available_tickers_from_ftp(my.date = "2016-10-30",
type.market = "equity", max.dl.tries = 10)
head(tickers_equity, n = 10)
```

Criando um vetor com as 6 ações mais negociadas em 30/10/2016.

```{r}
top_6 <- c(as.character(head(tickers_equity$tickers)))
print(top_6)
```

Baixando os dados

```{r, eval = FALSE}
dados_top6 <- ghfd_get_HF_data(top_6, type.market = "equity", first.date = as.Date("2014-11-03"), last.date = as.Date("2016-10-30"), first.time = "9:00:00", last.time = "18:00:00", type.output = "agg", agg.diff = "1 hour", dl.dir = "ftp files", max.dl.tries = 10, clean.files = FALSE)
save(dados_top6, file = 'dados_top6.Rda')
head(dados_top6, n=6)
```
```{r}
load('dados_top6.Rda')
dim(dados_top6)
str(dados_top6)
```
Agora irei criar um banco de dados para cada ação e depois obter os log retornos.

```{r separando dados, tidy = TRUE, tidy.opts = list(width.cutoff = 65)}
library(dplyr)
dados_ITSA4 <- filter(dados_top6, InstrumentSymbol == "ITSA4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_PETR4 <- filter(dados_top6, InstrumentSymbol == "PETR4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_ITUB4 <- filter(dados_top6, InstrumentSymbol == "ITUB4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_BBDC4 <- filter(dados_top6, InstrumentSymbol == "BBDC4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_ABEV3 <- filter(dados_top6, InstrumentSymbol == "ABEV3") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price))) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_BBSE3 <- filter(dados_top6, InstrumentSymbol == "BBSE3") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
```
Removendo `NA`s.

```{r}
dados_BBSE3 <- dados_BBSE3[2:3778,]
dados_ABEV3 <- dados_ABEV3[2:3778,]
dados_BBDC4 <- dados_BBDC4[2:3778,]
dados_ITUB4 <- dados_ITUB4[2:3778,]
dados_PETR4 <- dados_PETR4[2:3777,]
dados_ITSA4 <- dados_ITSA4[2:3778,]
```
Criando matriz com os dados diários.

```{r}
matriz_logrtn <- data.frame(lrtn_ITSA4 = dados_ITSA4$log_retorno, lrtn_ITUB4 = dados_ITUB4$log_retorno, lrtn_BBDC4 = dados_BBDC4$log_retorno, lrtn_ABEV3 = dados_ABEV3$log_retorno, lrtn_BBSE3 = dados_BBSE3$log_retorno)
summary(matriz_logrtn)
cor(matriz_logrtn)
```

```{r}
library(MTS)
MTSplot(matriz_logrtn)
```
```{r}
head(matriz_logrtn)
```

\newgeometry{l=0cm, b=0cm, t=0cm, r=0cm}
```{r}
library(MTS)
ccm(matriz_logrtn)
```
\restoregeometry

```{r}
mq(matriz_logrtn)
```




