---
title: "Baixando e analisando dados de alta frequência"
author: 
- Lucca Simeoni Pavan \hspace{1cm} João Carlos de Carvalho
header-includes:
   - \setlength\parindent{24pt}
   - \usepackage[english, brazil]{babel}
   - \usepackage[utf8]{inputenc}
   - \usepackage{longtable}
   - \usepackage{booktabs}
date: \today
output: 
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
bibliography: bib_artigo_macroeconometria.bib
---

```{r setup, include=TRUE, tidy = TRUE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, fig.height = 4,
                warning = FALSE, message = FALSE, error = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 70))
```

# Ranking de negociações

```{r tickers, cache = TRUE}
library(GetHFData)
tickers_equity <- ghfd_get_available_tickers_from_ftp(my.date = "2016-10-30",
type.market = "equity", max.dl.tries = 10)
head(tickers_equity, n = 10)
```

Criando um vetor com as 6 ações mais negociadas em 30/10/2016.

```{r}
top_6 <- c(as.character(head(tickers_equity$tickers)))
print(top_6)
```

Baixando os dados

```{r, eval = FALSE}
dados_top6 <- ghfd_get_HF_data(top_6, type.market = "equity", first.date = as.Date("2014-11-03"), last.date = as.Date("2016-10-30"), first.time = "9:00:00", last.time = "18:00:00", type.output = "agg", agg.diff = "1 hour", dl.dir = "ftp files", max.dl.tries = 10, clean.files = FALSE)
save(dados_top6, file = 'dados_top6.Rda')
head(dados_top6, n=6)
```
```{r}
load('dados_top6.Rda')
dim(dados_top6)
str(dados_top6)
```
Agora irei criar um banco de dados para cada ação e depois obter os log retornos.

```{r separando dados, tidy = TRUE, tidy.opts = list(width.cutoff = 65)}
library(dplyr)
dados_ITSA4 <- filter(dados_top6, InstrumentSymbol == "ITSA4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_PETR4 <- filter(dados_top6, InstrumentSymbol == "PETR4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_ITUB4 <- filter(dados_top6, InstrumentSymbol == "ITUB4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_BBDC4 <- filter(dados_top6, InstrumentSymbol == "BBDC4") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_ABEV3 <- filter(dados_top6, InstrumentSymbol == "ABEV3") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price))) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
dados_BBSE3 <- filter(dados_top6, InstrumentSymbol == "BBSE3") %>% select( SessionDate, weighted.price) %>% mutate( log_retorno = log(weighted.price) - lag(log(weighted.price)))
```
Removendo `NA`s.

```{r}
dados_BBSE3 <- dados_BBSE3[2:3778,]
dados_ABEV3 <- dados_ABEV3[2:3778,]
dados_BBDC4 <- dados_BBDC4[2:3778,]
dados_ITUB4 <- dados_ITUB4[2:3778,]
dados_PETR4 <- dados_PETR4[2:3777,]
dados_ITSA4 <- dados_ITSA4[2:3778,]
```

# Descrição dos Dados

Representação dos preços.

```{r}
matriz_preco <- data.frame(ITSA4 = (dados_ITSA4$weighted.price), ITUB4 = (dados_ITUB4$weighted.price), BBDC4 = (dados_BBDC4$weighted.price), ABEV3 = (dados_ABEV3$weighted.price), BBSE3 = (dados_BBSE3$weighted.price))
library(BMR)
gtsplot(matriz_preco)
summary(matriz_preco)
cov(matriz_preco)
```



Criando matriz de log dos preços.



```{r}
matriz_logpreco <- data.frame(ITSA4 = log(dados_ITSA4$weighted.price), ITUB4 = log(dados_ITUB4$weighted.price), BBDC4 = log(dados_BBDC4$weighted.price), ABEV3 = log(dados_ABEV3$weighted.price), BBSE3 = log(dados_BBSE3$weighted.price))
library(BMR)
gtsplot(matriz_logpreco)
summary(matriz_logpreco)
cov(matriz_logpreco)
```

Criando matriz com os dados log retorno.

```{r}
matriz_logrtn <- data.frame(ITSA4 = dados_ITSA4$log_retorno, ITUB4 = dados_ITUB4$log_retorno, BBDC4 = dados_BBDC4$log_retorno, ABEV3 = dados_ABEV3$log_retorno, BBSE3 = dados_BBSE3$log_retorno)
summary(matriz_logrtn)
cov(matriz_logrtn)
cor(matriz_logrtn)
```

```{r}
library(BMR)
gtsplot(matriz_logrtn)
```
```{r}
head(matriz_logrtn)
```
# Testes de Estacionariedade
 
```{r stat1, results='hide'}
library(BMR)
library(knitr)
stat1 <- stationarity(matriz_preco, 4, 8)
```

```{r}
kable(stat1$KPSS, caption = "Teste KPSS (preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat1$ADF, caption = "Teste ADF (preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat1$ADFLags, caption = "Defagens do teste ADF (preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
```

```{r stat2, results='hide'}
stat2 <- stationarity(matriz_logpreco, 4, 8)
```

```{r}
kable(stat2$KPSS, caption = "Teste KPSS (log preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat2$ADF, caption = "Teste ADF (log preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat2$ADFLags, caption = "Defagens do teste ADF (log preço)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
```


```{r stat3, results='hide'}
stat3 <- stationarity(matriz_logrtn, 4, 8)
```

```{r}
kable(stat3$KPSS, caption = "Teste KPSS (log retorno)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat3$ADF, caption = "Teste ADF (log retorno)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
kable(stat3$ADFLags, caption = "Defagens do teste ADF (log retorno)", format = "latex", booktabs = TRUE, longtable = TRUE, digits = 2)
```

```{r, fig.height=2}
library(BMR)
gacf(matriz_logrtn)
gpacf(matriz_logrtn)
save(matriz_preco, file = "matriz_preco.Rda")
save(matriz_logrtn, file = "matriz_logrtn.Rda")
```
```{r, fig.height=8}
acf(matriz_logrtn)
acf(matriz_logrtn, type = "partial")
```
```{r, fig.height=8}
library(MVN)
uniPlot(matriz_logrtn, type = "qqplot")
uniPlot(matriz_logrtn, type = "box")
uniPlot(matriz_logrtn, type = "scatter")
```

```{r, fig.height=6}
uniPlot(matriz_logrtn, type = "histogram")
```

```{r}
library(MVN)
library(fBasics)
uniNorm(matriz_logrtn)
jarqueberaTest(matriz_logrtn$ITSA4)
jarqueberaTest(matriz_logrtn$ITUB4)
jarqueberaTest(matriz_logrtn$BBDC4)
jarqueberaTest(matriz_logrtn$ABEV3)
jarqueberaTest(matriz_logrtn$BBSE3)
```
```{r}
library(MTS)
mq(matriz_logrtn, lag = 10)
```

