---
header-includes:
   - \setlength\parindent{24pt}
   - \usepackage[english, brazil]{babel}
   - \usepackage[utf8]{inputenc}
   - \usepackage{longtable}
   - \usepackage{booktabs}
   - \usepackage{indentfirst}
output: 
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: no
bibliography: bib_artigo_macroeconometria.bib
csl: C:/Users/Lucca/GoogleDrive/DOUTORADO_UFPR/Macroeconometria/artigo_macroeconometria/artigo_lucca_joao/abnt-ufpr.csl
---

```{r setup, include=TRUE, tidy = TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, fig.height = 4,
                warning = FALSE, message = FALSE, error = FALSE, tidy = TRUE, tidy.opts = list(width.cutoff = 70))
```

# Revisão de Literatura: Estudos de volatilidade no mercado financeiro brasileiro


Pesquisas usando dados de alta frequência ou dados com informações financeiras intradiárias vêm sendo feitas no Brasil, principalmente usando informações sobre o mercado de ações. Com este tipo de dado foram realizados diversos estudos, em grande parte que estudam a volatilidade do retorno nos ativos financeiros. No caso de mercado de ações os estudos tratam sobre  o melhor modelo de ajuste e acurácia de previsão.  Já o mercado de futuros, mais especifivamente o de *commodities*, os estudos têm sido feitos para entender as características de volatilidade do preço dos ativos, mas com dados de peridiocidade predominantemente mensais ou semanais.

@moreira_o_2004 investigaram o uso de dados de alta frequência na estimação da volatilidade diária e intradiária do IBOVESPA e no cálculo do valor em risco (VaR). Para isso usaram os modelos GARCH e EGARCH em conjunto com métodos determinísticos de filtragem de sazonalidade para a previsão da volatilidade e do VaR intradiários. Os autores compararam seus resultados com o método não paramétrico e no cálculo do VaR diário, dois métodos foram usados. O primeiro utiliza o desvio padrão amostral com janela móvel e o segundo usa alisamento exponencial. No cálculo do VaR diário, os dois métodos usados baseados em informações intradiárias apresentaram bom desempenho. Ao calcularem o VaR intradiário, seus resultados mostraram que a filtragem do padrão sazonal é indispensável à obtenção de resultados satisfatórios por meio dos modelos GARCH e EGARCH. A série utilizada pelos autores é o índice IBOVESPA, registrados a cada 15 minutos durante o período de 06/04/1998 a 19/07/2001 e utilizaram o retorno logarítmico para as estimações. Os autores também concluíram que o filtro de sazonalidade do intervalo intradiário é mais importante para melhorar os resultados das estimações do que o filtro referente ao dia da semana.

@carvalho_modeling_2006 estimaram a volatilidade diária dos cinco ativos mais negociados na bolsa de valores de São Paulo. Os autores utilizaram dados intradiários e utilizaram o estimador de variância realizada. Os autores concluíram que  os retornos diários padronizados pela volatilidade realizada são aproximadamente normais. Também concluíram que as log-volatilidades também apresentam distribuições bem próximas da normal. Em contraposição com a literatura corrente até então, não encontraram evidências de memória de longo prazo na série de volatilidade e um modelo de memória curta foi suficiente para os autores modelarem e preverem  as séries diárias de volatilidade. Os modelo usados pelos autores foram o retorno logarítimico padrozinado, EWMA, GARCH, EGARCH e GJR-GARCH.

@ceretta_intraday_2011 inestigaram como a especificação da distribuição influencia a performance da previsão da volatilidade em dados intradiários do IBovespa, usando o modelo APARCH. As previsões dos autores foram realizadas supondo seis distribuições dinstintas: normal, normal assimétrica, *t-student*, *t-student* assimétrica, generalizada e generalizada assimétrica. Os resultados obtidos mostraram que o modelo com distribuição *t-student* assimétrica foi o que melhor se ajustou aos dados dentro da amostra, porém, na previsão fora da amostra, o modelo com distribuição normal apresentou melhor desempenho. @ceretta_intraday_2011 encontraram também que  uma modelagem feita a partir de uma série longa pode incorporar efeitos atípicos no modelo, viesando a previsão. Os autores apontam como  uma possível solução realizar um ajuste do modelo utilizando uma série menor, com menos efeitos esporádicos, em que, segundo eles, a previsão poderia ter um comportamento mais aproximado ao habitual para a série, o que minimizaria  o efeito de eventuais variações acentudas. Outro fato destacado pelos autores é que  o modelo que melhor se ajusta, nem sempre fornecerá  a melhor previsão. Isto, conforme @ceretta_intraday_2011 , ressalta  a importância da comparação entre os modelos  estudados fora da amostra para encontrar o modelo que melhor prevê o comportamento futuro da série. A partir disso os autores sugerirm que o contexto macroeconômico poderia influenciar tanto o ajuste quanto a previsão de uma série financeira.

@junior_modeling_2013 usaram dados intradiários com intervalo de tempo de 5, 15 e 30 minutos para as ações mais comercializadas do índice BOVESPA. Seu artigo analisou dois modelos para estimação e previsão da volatilidade realizada: o modelo autorregressivo heterogêneo de volatilidade realizada (HAR-RV) e o modelo de amostragem de dados mistos (MIDAS-RV). Os autores compararam previsões dentro e fora da amostra e encontraram melhores resultados com o modelo MIDAS-RV para previsões dentro da amostra. Para previsões fora da amostra  não encontraram diferença estatísticamente significativa entre os modelos. Por fim os autores acharam evidência de que  o uso de volatilidade realizada induz a distribuições dos retornos padronizados próximas da normal.

@santos_volatility_2014 compararam diversos tipos de medidas de volatilidade e seus modelos de previsão, das famílias de modelos MIDAS-RV e HAR-RV. Realizaram comparações em termos da acurácia de previsão da volatilidade fora da amostra e usaram também uma combinação dos dois modelos. Para isso captaram dados intradiários do índice IBOVESPA e calcularam medidas de volatilidade como variância realizada, variação potência realizada e variação bi-potência realziada para serem usados como regressores em ambos os modelos. Para a estimação usaram um procedimento não paramétrico para mensurar separadamente  a variação da trajetória contínua da amostra e a parte de salto descontínuodo de processo  de variação quadrático. Seus resultados em termos de erro quadrático médio sugerem que regressores envolvendo medidas de volatilidade que são robustos a saltos são melhores para previsão de volatilidade futura. Encontraram ainda que previsões    baseadas nestes regressores não são estatísticamente diferentes daqueles baseados em variância realizada. Por fim, acharam que a performance de previsão das três abordagens são estatísticamente equivalentes.

@vicente_assessing_2014 examinaram se investidores possuem percepções diferentes sobre a volatilidade diária de um ativo. Para isso, definiram a volatilidade percebida pelo investidor como a distribuição dos desvios-padrão dos retornos diários calculados de preços intradiários coletados aleatoriamente. Os autores encontraram que esta distribuição tem uma alto grau de dispersão, o que significa que diferentes investidores podem não compartilhar a mesma opinião a respeito da variabilidade do mesmo ativo. Entretanto, segundo @vicente_assessing_2014  a volatilidade de preços de fechamento é geralente menor que a mediana da volatilidade percebida pelo investidor, enquanto a volatilidade de preço de abertura é maior. Seus resultados indicaram que as volatilidades usando amostras diárias tradicionais de retornos diários podem não ser bons insumos de modelos financeiros, já que, conforme os autores,  eles podem não capturar adequadamente o risco em que os investidores são expostos.

@ziegelmann_selection_2014 exploraram diferentes estimadores de matriz de covariância, tanto a condicional quanto a incondicional, obtidas por dados intradiários. Tais medidas foram usadas para obter um portfólio de variância mínima. Os dados foram coletados de forma sincronizada e não sincronizada. Para fins de comparação os autores também usaram dados diários. Em seu trabalho também avaliaram as performances fora da amostra  dos índices obtidos de um portfólio de 30 ações comercializadas na BMF&BOVESPA. Seus resultados mostraram que o estimador da matriz de variância condicional dos retornos usando o modelo escalar vt-VECH baseado em dados de alta frequência leva a melhoras substanciais de estimação, reduzindo o risco de portfólio, aumentando o retorno médio ajustado pelo risco e reduzindo o *turnover* financeiro.

@araujo_estimacao_2015 proporam uma combinação da estimação de volatilidade dos modelos HAR-RV e MIDAS-RV para responder a seguinte questão: o tomador de decisão deveria selecionar a melhor projeção ou projetar o futuro por meio da combinação de múltiplas projeções? Seus resultados mostraram que o modelo HAR-RV apresentou melhor performance para a amostra de dados utilizada. Ao comparar as projeções individuais e métodos de combinação, a combinação de pesos iguais apresentou melhor performance.

Percebe-se na literatura consultada, que os estudos que têm como onjeto o mercado de ações são em sua maioria bastante técnicos e preocupados em testar diversos métodos e modelos de estimação. A principal preocupação deste tipo de pesquisa é obter o mehor ajuste de modelo e a melhor previsão possível, usando os diversos métosos dispostos na literatura para comparar seus restultados. Outra questão de destque é que na literatura empírica sobre mercado de ações, o discussão dobre a peridiocidade dos dados, principalmente de dados intradiários é bastante difundida e objeto recorrente de análise. Já os estudos sobre preços e retorno de commodities possuem uma característica um pouco diferente.

## Estudos empíricos sobre volatilidade para *commodities*.


Devido à forma de obtnção dos dados, os estudos que tratam a volatilidade doretorno de *commodities* feitos no Brasil usam dados geralmente semanais ou mensais. Estes estudos possuem preocupação principal em estudar a persistência de choques, assimetria da volatilidade eo efeito alavancagem. Como método, nos estudos que têm como objeto retornos de *commodities* é comum encontrar modelos da família ARCH, sendo que  não foram encontrados outros tipos de modelos como HAR-RV e MIDAS-RV na literatura consultada.

@silva_uma_2005 examinaram o processo de volatilidade dos retornos do café e da soja no Brasil usando dados mensais. Seus resultados segurem fortes sinais de persistência e assimetria na volatilidade de ambas as séries. Além disso, afirmam que seus resultados indicam que a implementação de políticas que criem e facilitem o acesso e estimulem a utilização de instrumentos de *hedging* baseados no mercado podem ser estratégias adequadas para tais setores lidarem com a persistência de choques e volatilidade pronunciadas para os retornos destas *commodities*.

@lima_previsao_2007 modelaram a previsão com diferenciação inteira e fracionária, utilizando dados de preços futuros de *commodities* agrícolas. Os autores comparam as estimações de modelos ARMA e ARIMA com os resultados obtidos pelo modelo ARFIMA. Para avaliar o poder de previsão, os autores usaram o critério de erro quadrado médio e também estimaram o termo de diferenciação *d* para examinar as características de longo prazo das séries. Seus resultados indicaram que todas as séries de retornos de preços futuros são estacionárias. Encontraram ainda que os modelos ARFIMA mostraram melhor poder de previsão.

@silva_alise_2008 analisou a volatilidade do retorno dos preços de boi gordo no Estado de São Paulo. O autor examinou a persistência dos choques e assimetrias na sua volatilidade usando os modelos ARCH e GARCH. Seus resultados mostraram reações de persistência e assimetria na volatilidade em que choques negativos e positivos têm impactos diferentes sobre a volatilidade dos retornos dos preços do boi gordo. Seus resultados foram corroborados pelos modelos EGARCH e TGARCH.

@teixeira_dinamica_2008 usou a família de modelos ARCH para analisar o comportamento do retorno do cacau, do boi gordo e do café. Seus resultados indicaram fortes sinais de persistÊncia para as três *commodities* e que os choques levam um longo tempo para dissipar-se. Os autores ainda constataram que choques positivos e negativos têm efeitos diferentes sobre a volatilidade, então os mercados são assimétricos, e que o boi gordo e o cacau  sofrem o efeito alavancagem.

@pereira_volatilidade_2010 analisaram os retornos da soja, café e boi gordo. Para isso  usaram  modelos ARCH e calcularam o *Value-at-Risk (VaR)*. Seus resultados indicaram que a variabilidade das três *commodities* possui dependência condicional e que exite grande persistência  na resposta aos choques na variância. Observaram também que os retornos do café e soja  tiveram assimetrias nos choques positivos e negativos, embora não encontraram o efeito alavancagem. As medidas dos  *VaR* encontradas pelos autores mostraram maior potencial de perda para os produtores de café, seguidos pelos da soja e de boi gordo.

@bodra_modelo_2012 usou um modelo de volatilidade estocástica com saltos para  estudar a dinâmica de preços do milho e da soja. Seus resultados mostraram que um modelo de volatilidade estocástica pode ser bem ajustado ao mercado de *commodities* agrícolas e que o processo de *jump dffusion* pode representar bem os saltos deste mercado. Os autores usaram um modelo de Monte Carlo de mínimos quadrados (LSM) para a precificação das opções que foram utilizadas para formular uma estratégia de *hedge* de uma posição física de milho e de soja, sendo que a eficiência dessa estratégia foi comparada com estratégias já disponíveis no mercado.

@freitas_volatilidade_2015 analisaram a persistência, a alavancagem e a variância condicional dos retornos de commodities agropecuárias, usando o modelo APARCH. As séries estudadas pelos autores foram, o açúcar, a soja, o milho, o café, o algodão, o arroz, o trigo, o frango, o boi gordo e o bezerro. Os autores encontraram que não ocorreu alavancagem nas séries e que a variância  condicional foi assimétrica nos retornos do etanol, do café, do algodão, do boi gordo e do bezerro. Acharam também que as volatilidades mais intensas, embora com convergência à sua média histórica, ocorreram nos retornos do açúcar, da soja, do café, do trigo, do frango e do boi gordo. As maiores volatilidades incondicionais encontradas pelos autores foram dos retornos do etanol, do frango, do algodão, da soja e do açúcar.

Conforme identificado na revisão de literatura, os trabalhos sobre a mercado de derivativos de *commodities* usam predominantemente dados semanais e mensais, sendo que dados de alta frequência com peridiocidade intradiária não ofi feito até então para a  economia brasileira. Conforme @moreira_o_2004 a utilização de dados intradiários melhor o ajuste do modelo e a previsibilidade da série estudada, já que estes dados incorporam mais informações sobre  a microestrutura do mercado financeiro. E segundo @vicente_assessing_2014 os dados diários e consequentemente dados semanais e mensais, não capturam todo o risco e  incerteza que o agente econômico está expostos ao lidar com instrumentos financeiros. Com isso, justifica-se um estudo que use dados com informações intradiárias para estudar o mercado de *commodities*, sendo que assim contribuições sobre a existência ou não de alavancagem financeira, pode ser feitas, já qe os estudos feitos até então, não utilizaram esta peridiocidade dos dados.



\pagebreak

Autores         |Objeto           |Periodicidade    | Método
-------------   | -------------   |-----------      |------------------
    @moreira_o_2004 | IBOVESPA        |  15 min e 1 dia |GARCH, EGARCH
@carvalho_modeling_2006| Top 5 empresas IBOVESPA|15 min|EWMA, GARCH, EGARCH, GJR-GARCH, log retorno padronizado
@ceretta_intraday_2011|IBOVESPA |    15 min  |APARCH
@junior_modeling_2013|Top 5 empresas IBOVESPA|5, 15 e 30 min|HAR-RV e MIDAS-RV
@morais_estimating_2014|Top 2 BMF&BOVESPA|5 min  |GARCH, EGARCH, CGARCH e TGARCH
@santos_volatility_2014| IBOVESPA | 15 min| HAR, MIDAS e combinação HAR-MIDAS
@vicente_assessing_2014|84 empresas da BMF&BOVESPA|Amostragem aleatória de preços em um intervalo|Análise exploratória da Volatilidade Realizada
@ziegelmann_selection_2014|Índice de 30 ações BMF&BOVESPA| 5 a 120 min| Covariância realizada, vt_VECH escalar e MRK
@araujo_estimacao_2015| IBOVESPA |5 min| HAR_RV, MIDAS-RV e combinação HAR-MIDAS
@silva_uma_2005|café e soja| mensal   |GARCH, EGARCH e TARCH
@lima_previsao_2007|  Açúcar, café, boi gordo, milho e soja| ???  | ARMA, ARIMA e ARFIMA; Arch e GARCH
@silva_alise_2008|boi gordo|   diária |ARCH, GARCH, EGARCH e TGARCH
@teixeira_dinamica_2008|cacau, café e boi gordo| diária |GARCH, EGARCH, TARCH
@pereira_volatilidade_2010|Soja, café e boi gordo|semanal|EGARCH, TGARCH e GARCH-M
@bodra_modelo_2012| milho e soja| mensal| Volatilidade estocástica e saltos
@freitas_volatilidade_2015|Açúcar, soja,  milho,  café,  algodão,  arroz,  trigo,  frango,  boi gordo e  bezerro|semanal|APARCH
Table: Resumo dos estudos de volatilidade no mercado financeiro brasileiro.

Fonte: Elaboração dos autores









\pagebreak

# Referências {-}
\setlength{\parindent}{0in}
